In [22]:
import numpy as np

hello = 'Hello, world.'
print(hello)

Hello, world.


In [23]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [24]:
arr2 = np.array([[1,2], [3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [25]:
arr3 = np.array([1,2,3,4,5,6], ndmin=3)
print(arr3)

arr_float = np.array(arr3, dtype=float)
print(arr_float)

[[[1 2 3 4 5 6]]]
[[[1. 2. 3. 4. 5. 6.]]]


In [26]:
arr_bool = np.array([0,1,0,1], dtype=bool)
print(arr_bool)

[False  True False  True]


In [27]:
# get the array dimensions
print(arr3)
print(arr3.shape)

[[[1 2 3 4 5 6]]]
(1, 1, 6)


In [28]:
arr4 = np.array(arr2)
print(arr4)
print(arr4.shape)

arr4.shape = (4,1)
print(arr4)
print(arr4.shape)

[[1 2]
 [3 4]]
(2, 2)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [29]:
arr5 = arr2.reshape(4,1)
print(arr5)

[[1]
 [2]
 [3]
 [4]]


In [30]:
a = np.arange(5,30,2)
print(a)
print(a[:5])
print(a[2:5])
print(a[7:])

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 5  7  9 11 13]
[ 9 11 13]
[19 21 23 25 27 29]


In [31]:
print(a[::-1])

[29 27 25 23 21 19 17 15 13 11  9  7  5]


In [32]:
b = np.array([[1,2,3,4,5], [2,4,6,8,10],
[3,6,9,12,15], [5,10,15,20,25], [6,12,18,24,30]])
print(b, '\n')
print(b[:1], '\n') 
print(b[1:], '\n') 
print(b[::2], '\n') 
print(b[:1, :2])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]] 

[[1 2 3 4 5]] 

[[ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]] 

[[ 1  2  3  4  5]
 [ 3  6  9 12 15]
 [ 6 12 18 24 30]] 

[[1 2]]


In [33]:
k = np.array([[1,2,3,4], [2,4,6,8],
[3,6,9,12]])

#print(k)

ksub = k[:3, :2]
#print(k, '\n')
#print(ksub)

ksub[1,0] = 100
print(ksub)
print(k)

[[  1   2]
 [100   4]
 [  3   6]]
[[  1   2   3   4]
 [100   4   6   8]
 [  3   6   9  12]]


In [34]:
m = np.array([9,18,27,36])
n = np.array([10,20,30,40])
o = np.array([7,14,21,28])

print(m,'\n', n, '\n', o)
print(np.concatenate([m,n]))
print(np.concatenate([m,n,o]))

[ 9 18 27 36] 
 [10 20 30 40] 
 [ 7 14 21 28]
[ 9 18 27 36 10 20 30 40]
[ 9 18 27 36 10 20 30 40  7 14 21 28]


In [35]:
print(np.vstack([m,n,o]))
print(np.hstack([m,n,o]))

[[ 9 18 27 36]
 [10 20 30 40]
 [ 7 14 21 28]]
[ 9 18 27 36 10 20 30 40  7 14 21 28]


In [36]:
r = np.arange(8)
print("r =", r)
print("r + 10 =", r + 10)
print("r / 2 =", r / 2)

r = [0 1 2 3 4 5 6 7]
r + 10 = [10 11 12 13 14 15 16 17]
r / 2 = [0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [37]:
s = np.arange(100)

def div_by_2(array):
    v = np.empty(len(array))
    for i in range(len(array)):
        v[i] = i /2
    return v

r2 = div_by_2(r)
print(r2)

s2_numpy = s / 2
%timeit s2_numpy = s / 2
print(len(s2_numpy))

s2_loop = div_by_2(s)
%timeit s2_loop = div_by_2(s)
print(len(s2_loop))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5]
3.42 µs ± 61.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
100
17.3 µs ± 435 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
100


In [38]:
X = np.random.random(1000)
print(np.sum(X))

x_range = (X.min(), X.max())
print(x_range)

509.84916383416936
(0.0022995895148677503, 0.9996766126350027)


In [39]:
Y = np.random.random((3,4))
print(Y, '\n')

print(Y.sum(axis=0), '\n')
print(Y.sum(axis=1))

[[0.63713346 0.06727692 0.59180048 0.74508809]
 [0.17130833 0.71009388 0.17683449 0.18485247]
 [0.87727176 0.99859765 0.79142694 0.25374275]] 

[1.68571354 1.77596844 1.56006191 1.18368331] 

[2.04129894 1.24308916 2.92103909]


In [40]:
Z = np.random.randint(1,10,100)
print(Z)

print("mean =", np.mean(Z))
print("variance =", np.var(Z))
print("standard deviation =", np.std(Z))
print("median =", np.median(Z))

[4 4 2 3 5 2 7 9 8 5 7 1 1 8 1 6 2 4 5 8 3 5 5 1 4 4 8 4 4 7 8 3 8 2 5 8 5
 2 6 3 3 1 7 2 3 8 2 6 4 1 1 6 6 6 1 2 1 1 4 8 1 3 5 4 9 9 3 5 4 5 4 7 9 4
 9 5 5 4 9 6 6 8 1 7 4 3 1 8 2 2 4 5 9 4 1 3 6 8 2 5]
mean = 4.59
variance = 6.161899999999999
standard deviation = 2.482317465595406
median = 4.0
